/** Get Golden Account Details */
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_D 
WHERE GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = '10000000655297'
    AND GOLDEN_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y'
    

/** Get Golden Account Attributes */
SELECT GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ID, GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ATTR_LOV_ID, 
	GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_BRIDGE
JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D ON GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ATTR_LOV_ID = GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID AND GOLDEN_ACCOUNT_ATTR_LOV_D.CURRENT_VERSION_FLAG = 'Y'
JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D ON GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID = GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID AND GOLDEN_ACCOUNT_ATTR_TYPE_D.CURRENT_VERSION_FLAG = 'Y' 
WHERE GOLDEN_ACCOUNT_ATTR_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
	AND GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ID = 10000000655297;


/** recentAccountChanges -- sql modified */
SELECT PENDINGAPPROVALATTRIBUTE.ATTRIBUTE, PENDINGAPPROVALATTRIBUTE.NEWVALUE, PENDINGAPPROVALATTRIBUTE.CURRENTVALUE, PENDINGAPPROVALATTRIBUTE.SUBMITTED_DATE, 
	PENDINGAPPROVALATTRIBUTE.SUBMITTED_BY, PENDINGAPPROVALATTRIBUTE.APPROVED_DATE, PENDINGAPPROVALATTRIBUTE.APPROVED_BY
FROM PRESENTATION.GOLDEN_ACCOUNT_D 
    INNER JOIN PRESENTATION.PENDINGAPPROVALATTRIBUTE ON GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = TRY_CAST(PENDINGAPPROVALATTRIBUTE.GOLDENACCOUNTNUMBER AS INTEGER)
WHERE GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = '10000028388107' AND GOLDEN_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y' AND PENDINGAPPROVALATTRIBUTE.ISAPPROVED = 1
ORDER BY PENDINGAPPROVALATTRIBUTE.PENDINGAPPROVALATTRIBUTE_PKEY DESC

/** xref accounts */
SELECT CUSTOMER_ACCOUNT_D.ACCOUNT_ID, CUSTOMER_ACCOUNT_D.ACCOUNT_NUMBER, CUSTOMER_ACCOUNT_D.ACCOUNT_NAME, CUSTOMER_ACCOUNT_D.LOGITECH_ACCOUNT_ID, CUSTOMER_ACCOUNT_D.COUNTRY, 
	CUSTOMER_ACCOUNT_D.ZYME_ID, CUSTOMER_ACCOUNT_D.VALID_ZYME_ID, CUSTOMER_ACCOUNT_D.VALID_ZYME_BUSINESS_NAME, CUSTOMER_ACCOUNT_D.CHANNEL_POSITION, 
	CUSTOMER_ACCOUNT_D.MASTER_NAME, CUSTOMER_ACCOUNT_D.SOURCE_SYSTEM_NAME, CUSTOMER_ACCOUNT_D.CUST_NMBR_AT_DIST, CUSTOMER_ACCOUNT_D.UPDATED_DATE, CUSTOMER_ACCOUNT_D.CREATED_DATE,
	(SELECT CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END FROM PRESENTATION.PENDINGAPPROVALXREFACCOUNT WHERE PENDINGAPPROVALXREFACCOUNT.CUSTOMERACCOUNTPKEY = CUSTOMER_ACCOUNT_D.ACCOUNT_ID AND PENDINGAPPROVALXREFACCOUNT.ISREJECTED = 0 AND PENDINGAPPROVALXREFACCOUNT.ISAPPROVED = 0 ) AS CAN_REASSIGN_FLAG
FROM PRESENTATION.CUSTOMER_ACCOUNT_D
    INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_BRIDGE ON CUSTOMER_ACCOUNT_D.ACCOUNT_ID = GOLDEN_ACCOUNT_BRIDGE.ACCOUNT_ID AND GOLDEN_ACCOUNT_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
WHERE GOLDEN_ACCOUNT_BRIDGE.GOLDEN_ACCOUNT_ID = '10000000655297'
AND CUSTOMER_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y'
ORDER BY CUSTOMER_ACCOUNT_D.ACCOUNT_ID

/** xref golden account search */
SELECT GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_NAME, GOLDEN_ACCOUNT_D.LOGITECH_ACCOUNT_ID, GOLDEN_ACCOUNT_D.ACCOUNT_NUMBER, GOLDEN_ACCOUNT_D.ZYME_ID, 
	GOLDEN_ACCOUNT_D.VALID_ZYME_ID, GOLDEN_ACCOUNT_D.COUNTRY, GOLDEN_ACCOUNT_D.REGION
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE CURRENT_VERSION_FLAG = 'Y'
	/*AND GOLDEN_ACCOUNT_D.ACCOUNT_NUMBER = 'AccountNumber'
	AND GOLDEN_ACCOUNT_D.LOGITECH_ACCOUNT_ID = 'LogitechAccountId'
	AND GOLDEN_ACCOUNT_D.VALID_ZYME_ID = 'ValidZymeId'
	AND GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_NAME like  '%GoldenAccountName%'
	AND GOLDEN_ACCOUNT_D.VALID_ZYME_BUSINESS_NAME like '%ValidZymeBusinessName%'
	AND GOLDEN_ACCOUNT_D.ERP_COUNTRY_CD = 'CountryCode'*/


/** xref account sites */
SELECT DISTINCT /*CUSTOMER_LOCATION_BRIDGE.CUSTOMER_LOCATION_BRIDGE_PKEY, CUSTOMER_SITE_D.CUSTOMER_SITE_PKEY,*/ CUSTOMER_SITE_D.ACCOUNT_SITE_USE_TYPE,
    CUSTOMER_SITE_D.PRIMARY_FLAG, CUSTOMER_SITE_D.ACCOUNT_SITE_USE_ID,
    CASE WHEN CUSTOMER_SITE_D.ACCOUNT_SITE_USE_TYPE = 'STORE' THEN CUSTOMER_SITE_D.SOURCE_SYSTEM_REFERENCE ELSE '' END AS STORE_NUMBER, 
    '' AS STORE_NAME, CUSTOMER_LOCATION_D.ADDRESS_LINE1, CUSTOMER_LOCATION_D.ADDRESS_LINE2, CUSTOMER_LOCATION_D.CITY, CUSTOMER_LOCATION_D.STATE,
    CUSTOMER_LOCATION_D.POSTAL_CD, CUSTOMER_LOCATION_D.COUNTRY_NAME, CUSTOMER_SITE_D.LOGITECH_ACCOUNT_ID, CUSTOMER_LOCATION_D.ZYME_LOCATION_ID   
 FROM PRESENTATION.CUSTOMER_SITE_D
    INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_BRIDGE ON (GOLDEN_ACCOUNT_BRIDGE.ACCOUNT_ID = CUSTOMER_SITE_D.ACCOUNT_ID AND GOLDEN_ACCOUNT_BRIDGE.CURRENT_VERSION_FLAG = 'Y')
    LEFT JOIN PRESENTATION.CUSTOMER_LOCATION_BRIDGE ON CUSTOMER_LOCATION_BRIDGE.TYPE_ID = CUSTOMER_SITE_D.ACCOUNT_SITE_USE_ID AND CUSTOMER_LOCATION_BRIDGE.TYPE = 'Customer Site' AND CUSTOMER_LOCATION_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
    INNER JOIN PRESENTATION.CUSTOMER_LOCATION_D ON CUSTOMER_LOCATION_D.LOCATION_ID = CUSTOMER_LOCATION_BRIDGE.LOCATION_ID AND CUSTOMER_LOCATION_D.CURRENT_VERSION_FLAG = 'Y'
WHERE 
    CUSTOMER_SITE_D.CURRENT_VERSION_FLAG = 'Y' AND GOLDEN_ACCOUNT_BRIDGE.GOLDEN_ACCOUNT_ID = '10000000655297'
ORDER BY CUSTOMER_SITE_D.ACCOUNT_SITE_USE_ID DESC


/** Account clasification --- "EMEA_CHANNEL_CLASSIFICATION" is duplicated in original query */
SELECT GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID, GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME,
	GOLDEN_ACCOUNT_ATTR.GOLDEN_ACCOUNT_ATTR_LOV_ID, GOLDEN_ACCOUNT_ATTR.GOLDEN_ACCOUNT_ATTR_VALUE,
    GOLDEN_ACCOUNT_ATTR.EFF_START_DATE, GOLDEN_ACCOUNT_ATTR.EFF_END_DATE
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D
LEFT JOIN (
	SELECT GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE, GOLDEN_ACCOUNT_ATTR_BRIDGE.EFF_START_DATE, GOLDEN_ACCOUNT_ATTR_BRIDGE.EFF_END_DATE
	FROM PRESENTATION.GOLDEN_ACCOUNT_D
		INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_BRIDGE ON GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ID AND GOLDEN_ACCOUNT_ATTR_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
		INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D ON GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID = GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ATTR_LOV_ID
	WHERE GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = '10000000655297' AND GOLDEN_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y'
) AS GOLDEN_ACCOUNT_ATTR ON GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID = GOLDEN_ACCOUNT_ATTR.GOLDEN_ACCOUNT_ATTR_TYPE_ID
WHERE GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME IN ('CHANNEL_CLASSIFICATION', 'PRICING_CLASSIFICATION', 'DR_CUSTOMER_TYPE', 'CHANNEL_GROUPING', 'CHINA_CITY',
        'BUSINESS_MARKET', 'BUYING_GROUP', 'B2B_CHANNEL', 'BUSINESS_TYPE', 'E_TAILER', 'APPLE_RESELLER', 'GFK_CLASSIFICATION', 'PRIORITY_CLASSIFICATION', 'T3_TERRITORY', 'TMall', 
        'EMEA_CHANNEL_CLASSIFICATION', 'AP_CHANNEL_CLASSIFICATION', 'LATAM_ACCOUNT_CLASSIFICATION', 'BRAZIL_ACCOUNT_CLASSIFICATION')
ORDER BY GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME


/** Reporting */
SELECT GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID, GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME,
	GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE,
	GOLDEN_ACCOUNT_ATTR_BRIDGE.EFF_START_DATE, GOLDEN_ACCOUNT_ATTR_BRIDGE.EFF_END_DATE,
	PENDINGAPPROVALATTRIBUTE.PENDINGAPPROVALATTRIBUTE_PKEY
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D
	LEFT JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D ON  GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID = GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID AND GOLDEN_ACCOUNT_ATTR_LOV_D.CURRENT_VERSION_FLAG = 'Y'
	INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_BRIDGE ON GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID = GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ATTR_LOV_ID AND GOLDEN_ACCOUNT_ATTR_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
	INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_D ON GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = '10000000655297' AND GOLDEN_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y' AND GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ID
	LEFT JOIN PRESENTATION.PENDINGAPPROVALATTRIBUTE ON GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME = PENDINGAPPROVALATTRIBUTE.ATTRIBUTE AND PENDINGAPPROVALATTRIBUTE.ISREJECTED = 0 AND PENDINGAPPROVALATTRIBUTE.ISAPPROVED = 0 AND PENDINGAPPROVALATTRIBUTE.GOLDENACCOUNTNUMBER = '10000000655297'
WHERE GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME IN ('EDI_CAPABILITY', 'REPORTING_FILE_FORMAT', 'REPORTING_FORMAT', 'REPORTING_FREQUENCY', 'REPORTING_MODE', 
    'STORE_LEVEL_DATA', 'REPORTING_RTS_QUANTITY', 'REPORTING_RTD_QUANTITY', 'REPORTING_T2_BACKLOG', 'TRANSACTION_DATE', 'POS_CUSTOMER', 'TRANSACTION_LEVEL_DATA', 'B2B_ST_AS_BT')
    AND GOLDEN_ACCOUNT_ATTR_TYPE_D.CURRENT_VERSION_FLAG = 'Y'
ORDER BY GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME


/** Account contacts -- Why here we need PENDAPP_CUSTOMER_CONTACTS_PKEY  */
SELECT DISTINCT CUSTOMER_CONTACTS_D.CONTACT_ID, CUSTOMER_CONTACTS_D.FIRST_NAME, CUSTOMER_CONTACTS_D.LAST_NAME, CUSTOMER_CONTACTS_D.EMPLOYEE_ID,
    CUSTOMER_CONTACTS_D.MIDDLE_NAME, CUSTOMER_CONTACTS_D.JOB_TITLE, CUSTOMER_CONTACTS_BRIDGE.MANAGER_FLAG, CUSTOMER_CONTACTS_BRIDGE.PRIMARY_MANAGER_FLAG,
    CUSTOMER_CONTACTS_BRIDGE.EFF_START_DATE, CUSTOMER_CONTACTS_BRIDGE.EFF_END_DATE/*, PENDINGAPPROVALCONTACTS.PENDAPP_CUSTOMER_CONTACTS_PKEY*/
FROM PRESENTATION.CUSTOMER_CONTACTS_D
    INNER JOIN PRESENTATION.CUSTOMER_CONTACTS_BRIDGE ON (CUSTOMER_CONTACTS_D.CONTACT_ID = CUSTOMER_CONTACTS_BRIDGE.CONTACT_ID AND CUSTOMER_CONTACTS_BRIDGE.TYPE_ID = '10000028469664'  AND CUSTOMER_CONTACTS_BRIDGE.TYPE = 'Golden Account' AND CUSTOMER_CONTACTS_BRIDGE.CURRENT_VERSION_FLAG = 'Y')
    /*LEFT JOIN PRESENTATION.PENDINGAPPROVALCONTACTS ON (CUSTOMER_CONTACTS_D.CUSTOMER_CONTACTS_PKEY = PENDINGAPPROVALCONTACTS.CUSTOMER_CONTACTS_PKEY AND PENDINGAPPROVALCONTACTS.ISREJECTED = 0 AND PENDINGAPPROVALCONTACTS.ISAPPROVED = 0 AND PENDINGAPPROVALCONTACTS.GOLDEN_ACCOUNT_ID = '10000000655297')*/
WHERE CUSTOMER_CONTACTS_D.CURRENT_VERSION_FLAG = 'Y'
ORDER BY CUSTOMER_CONTACTS_D.FIRST_NAME


/** search existing account contact */
SELECT CUSTOMER_CONTACTS_D.CONTACT_ID, CUSTOMER_CONTACTS_D.FIRST_NAME, CUSTOMER_CONTACTS_D.MIDDLE_NAME, CUSTOMER_CONTACTS_D.LAST_NAME, CUSTOMER_CONTACTS_D.EMPLOYEE_ID, 
	CUSTOMER_CONTACTS_D.CONTACT_TYPE, CUSTOMER_CONTACTS_D.STATUS, CUSTOMER_CONTACTS_D.EMPLOYEE_TYPE, CUSTOMER_CONTACTS_D.JOB_TITLE, CUSTOMER_CONTACTS_D.EMAIL_ADDRESS, 
	CUSTOMER_CONTACTS_D.PHONE_NO, CUSTOMER_CONTACTS_D.SALES_REP_FLAG
FROM PRESENTATION.CUSTOMER_CONTACTS_D
    INNER JOIN PRESENTATION.CUSTOMER_CONTACTS_BRIDGE ON CUSTOMER_CONTACTS_D.CONTACT_ID = CUSTOMER_CONTACTS_BRIDGE.CONTACT_ID 
    AND CUSTOMER_CONTACTS_BRIDGE.CURRENT_VERSION_FLAG = 'Y' 
    AND CUSTOMER_CONTACTS_BRIDGE.TYPE_ID = '10000028469664' AND CUSTOMER_CONTACTS_BRIDGE.TYPE = 'Golden Account'
WHERE CUSTOMER_CONTACTS_D.CURRENT_VERSION_FLAG = 'Y'
/*AND CUSTOMER_CONTACTS_D.EMPLOYEE_ID = ''
AND CUSTOMER_CONTACTS_D.FIRST_NAME like '%@First_Name%'
AND CUSTOMER_CONTACTS_D.LAST_NAME like '%@Last_Name%'
AND CUSTOMER_CONTACTS_D.MIDDLE_NAME  like '%@Middle_Name%'*/

SELECT MAX(PENDINGAPPROVALCONTACTS.PENDAPP_CUSTOMER_CONTACTS_PKEY) AS PKEY FROM PRESENTATION.PENDINGAPPROVALCONTACTS;

/** Add new contact */
INSERT INTO PENDINGAPPROVALCONTACTS ( 
			PENDINGAPPROVALCONTACTS.PENDAPP_CUSTOMER_CONTACTS_PKEY, 
			PENDINGAPPROVALCONTACTS.CONTACT_ID, 
			PENDINGAPPROVALCONTACTS.FIRST_NAME,
			PENDINGAPPROVALCONTACTS.MIDDLE_NAME, 
			PENDINGAPPROVALCONTACTS.LAST_NAME, 
			PENDINGAPPROVALCONTACTS.CONTACT_TYPE, 
			PENDINGAPPROVALCONTACTS.STATUS, 
			PENDINGAPPROVALCONTACTS.EMPLOYEE_ID,
            PENDINGAPPROVALCONTACTS.EMPLOYEE_TYPE,
            PENDINGAPPROVALCONTACTS.JOB_TITLE,
            PENDINGAPPROVALCONTACTS.EMAIL_ADDRESS,
            PENDINGAPPROVALCONTACTS.PHONE_NO,
            PENDINGAPPROVALCONTACTS.COLLECTOR_FLAG,
            PENDINGAPPROVALCONTACTS.SALES_REP_FLAG,
            PENDINGAPPROVALCONTACTS.EFF_START_DATE,
            PENDINGAPPROVALCONTACTS.EFF_END_DATE,
            PENDINGAPPROVALCONTACTS.ISREJECTED,
            PENDINGAPPROVALCONTACTS.ISAPPROVED,
            PENDINGAPPROVALCONTACTS.SUBMITTED_BY,
            PENDINGAPPROVALCONTACTS.SUBMITTED_DATE,
            PENDINGAPPROVALCONTACTS.SUBMITTED_COMMENT,
            PENDINGAPPROVALCONTACTS.SOURCE_SYSTEM_REFERENCE_TYPE,
            PENDINGAPPROVALCONTACTS.SOURCE_SYSTEM_REFERENCE,
            PENDINGAPPROVALCONTACTS.SOURCE_SYSTEM_NAME,
            PENDINGAPPROVALCONTACTS.MANAGER_FLAG,
            PENDINGAPPROVALCONTACTS.CUSTOMER_CONTACTS_PKEY,
            PENDINGAPPROVALCONTACTS.GOLDEN_ACCOUNT_ID,
            PENDINGAPPROVALCONTACTS.CURRENT_VERSION_FLAG,
            PENDINGAPPROVALCONTACTS.ACTION_TYPE,
            PENDINGAPPROVALCONTACTS.LOGITECH_ACCOUNT_ID,
            PENDINGAPPROVALCONTACTS.PRIMARY_MANAGER_FLAG,
            PENDINGAPPROVALCONTACTS.CREATED_BY
) VALUES (@maxPENDAPP_CUSTOMER_CONTACTS_PKEY, @p_CustomerContactId, @FIRST_NAME, @MIDDLE_NAME, @LAST_NAME, @CONTACT_TYPE, @STATUS, @EMPLOYEE_ID, 
        @EMPLOYEE_TYPE, @JOB_TITLE, @EMAIL_ADDRESS, @PHONE_NO, @COLLECTOR_FLAG, 
        @SALES_REP_FLAG, @EFF_START_DATE, @EFF_END_DATE, @ISREJECTED, @ISAPPROVED, @currentUserName, GETDATE(), @comment, 
        @SOURCE_SYSTEM_REFERENCE_TYPE, @SOURCE_SYSTEM_REFERENCE, @SOURCE_SYSTEM_NAME, @MANAGER_FLAG, @CUSTOMER_CONTACTS_PKEY, @p_GoldenAccountId, 'Y', 
        WHEN @p_CustomerContactId = 0 THEN "ADD" ELSE "ASSIGN" END, @LOGITECH_ACCOUNT_ID, @PRIMARY_MANAGER_FLAG, @currentUserName)


        
 
/** get account_number by godenAccountId */
SELECT DISTINCT(CUSTOMER_ACCOUNT_D.ACCOUNT_NUMBER), GOLDEN_ACCOUNT_BRIDGE.GOLDEN_ACCOUNT_ID
FROM PRESENTATION.CUSTOMER_ACCOUNT_D
INNER JOIN PRESENTATION.GOLDEN_ACCOUNT_BRIDGE ON GOLDEN_ACCOUNT_BRIDGE.ACCOUNT_ID = CUSTOMER_ACCOUNT_D.ACCOUNT_ID
WHERE CUSTOMER_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y'
	AND GOLDEN_ACCOUNT_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
	AND GOLDEN_ACCOUNT_BRIDGE.GOLDEN_ACCOUNT_ID = '10000000655297'
	AND CUSTOMER_ACCOUNT_D.ACCOUNT_NUMBER <> ''
ORDER BY CUSTOMER_ACCOUNT_D.ACCOUNT_NUMBER


/** Account Number change history */
SELECT PENDINGAPPROVALATTRIBUTE.NEWVALUE, PENDINGAPPROVALATTRIBUTE.CURRENTVALUE, PENDINGAPPROVALATTRIBUTE.STARTDATE,
	PENDINGAPPROVALATTRIBUTE.ENDDATE, PENDINGAPPROVALATTRIBUTE.SUBMITTED_BY, PENDINGAPPROVALATTRIBUTE.SUBMITTED_DATE,
    PENDINGAPPROVALATTRIBUTE.APPROVED_BY, PENDINGAPPROVALATTRIBUTE.APPROVED_DATE, PENDINGAPPROVALATTRIBUTE.ATTRIBUTE
FROM PRESENTATION.GOLDEN_ACCOUNT_D
INNER JOIN PRESENTATION.PENDINGAPPROVALATTRIBUTE ON GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = TRY_CAST(PENDINGAPPROVALATTRIBUTE.GOLDENACCOUNTNUMBER AS INTEGER)
WHERE GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID = 10000000655297
AND PENDINGAPPROVALATTRIBUTE.ISAPPROVED = '1'
AND PENDINGAPPROVALATTRIBUTE.ATTRIBUTE = 'ACCOUNT_NUMBER'

/*SELECT * FROM PRESENTATION.PENDINGAPPROVALATTRIBUTE WHERE GOLDENACCOUNTNUMBER = '10000000655297';*/

/*SELECT MAX(PENDINGAPPROVALATTRIBUTE.PENDINGAPPROVALATTRIBUTE_PKEY) FROM PRESENTATION.PENDINGAPPROVALATTRIBUTE*/

INSERT INTO PRESENTATION.PENDINGAPPROVALATTRIBUTE (
	PENDINGAPPROVALATTRIBUTE.PENDINGAPPROVALATTRIBUTE_PKEY,
    PENDINGAPPROVALATTRIBUTE.GOLDENACCOUNTNUMBER, 
    PENDINGAPPROVALATTRIBUTE.LOGITECH_PARTY_ID,
    PENDINGAPPROVALATTRIBUTE.ATTRIBUTE,
    PENDINGAPPROVALATTRIBUTE.CURRENTVALUE,
    PENDINGAPPROVALATTRIBUTE.NEWVALUE,
    PENDINGAPPROVALATTRIBUTE.STARTDATE,
    PENDINGAPPROVALATTRIBUTE.ENDDATE,
    PENDINGAPPROVALATTRIBUTE.SUBMITTED_BY,
    PENDINGAPPROVALATTRIBUTE.SUBMITTED_DATE,
    PENDINGAPPROVALATTRIBUTE.ISREJECTED,
    PENDINGAPPROVALATTRIBUTE.ISAPPROVED,
    PENDINGAPPROVALATTRIBUTE.SUBMITTED_COMMENT
) VALUES (
	'20309',
    '10000000655297',
    'A10978559',
    'ACCOUNT_NUMBER',
    '',
    '1020',
    '1900-01-01',
    '2100-12-31',
    'LB',
    current_date(),
    0,
    0,
    'TESTING comment'
)



SELECT DISTINCT(GOLDEN_ACCOUNT_D.LOGITECH_PARTY_NAME), GOLDEN_ACCOUNT_D.GOLDEN_ACCOUNT_ID, GOLDEN_ACCOUNT_D.LOGITECH_PARTY_ID, GOLDEN_ACCOUNT_D.ERP_COUNTRY_CD
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE GOLDEN_ACCOUNT_D.CURRENT_VERSION_FLAG = 'Y' 
AND GOLDEN_ACCOUNT_D.LOGITECH_PARTY_NAME  LIKE '%PFH%'
ORDER BY GOLDEN_ACCOUNT_D.LOGITECH_PARTY_NAME


/** request for adding new list of value  */
INSERT INTO PRESENTATION.PENDINGAPPROVALFORLOVS (
        GOLDEN_ACCOUNT_ATTR_TYPE_ID,
        NEWVALUE, 
        STARTDATE,
        ENDDATE,
        SUBMITTED_BY,
        SUBMITTED_DATE,
        SUBMITTED_COMMENT
    )
    VALUES (
        '4',
        'TEST2001',
        '1900-01-01',
        '2100-12-31',
        'LB',
        current_date(),
        'TESTING'
    );
   
   
 /** request for update golden account contact */
   
SELECT MAX(PENDAPP_CUSTOMER_CONTACTS_PKEY) + 1 FROM PRESENTATION.PENDINGAPPROVALCONTACTS; 

INSERT INTO PENDINGAPPROVALCONTACTS (
            PENDINGAPPROVALCONTACTS.PENDAPP_CUSTOMER_CONTACTS_PKEY,
            PENDINGAPPROVALCONTACTS.CONTACT_ID,
            PENDINGAPPROVALCONTACTS.FIRST_NAME,
            PENDINGAPPROVALCONTACTS.MIDDLE_NAME,
            PENDINGAPPROVALCONTACTS.LAST_NAME,
            PENDINGAPPROVALCONTACTS.CONTACT_TYPE,
            PENDINGAPPROVALCONTACTS.STATUS,
            PENDINGAPPROVALCONTACTS.EMPLOYEE_ID,
            PENDINGAPPROVALCONTACTS.EMPLOYEE_TYPE,
            PENDINGAPPROVALCONTACTS.JOB_TITLE,
            PENDINGAPPROVALCONTACTS.EMAIL_ADDRESS,
            PENDINGAPPROVALCONTACTS.PHONE_NO,
            PENDINGAPPROVALCONTACTS.COLLECTOR_FLAG,
            PENDINGAPPROVALCONTACTS.SALES_REP_FLAG,
            PENDINGAPPROVALCONTACTS.EFF_START_DATE,
            PENDINGAPPROVALCONTACTS.EFF_END_DATE,
            PENDINGAPPROVALCONTACTS.ISREJECTED,
            PENDINGAPPROVALCONTACTS.ISAPPROVED,
            PENDINGAPPROVALCONTACTS.SUBMITTED_BY,
            PENDINGAPPROVALCONTACTS.SUBMITTED_DATE,
            PENDINGAPPROVALCONTACTS.SUBMITTED_COMMENT,
            PENDINGAPPROVALCONTACTS.SOURCE_SYSTEM_REFERENCE_TYPE,
            PENDINGAPPROVALCONTACTS.SOURCE_SYSTEM_REFERENCE,
            PENDINGAPPROVALCONTACTS.SOURCE_SYSTEM_NAME,
            PENDINGAPPROVALCONTACTS.MANAGER_FLAG,
            PENDINGAPPROVALCONTACTS.CUSTOMER_CONTACTS_PKEY,
            PENDINGAPPROVALCONTACTS.GOLDEN_ACCOUNT_ID,
            PENDINGAPPROVALCONTACTS.CURRENT_VERSION_FLAG,
            PENDINGAPPROVALCONTACTS.ACTION_TYPE,
            PENDINGAPPROVALCONTACTS.LOGITECH_ACCOUNT_ID,
            PENDINGAPPROVALCONTACTS.PRIMARY_MANAGER_FLAG,
            PENDINGAPPROVALCONTACTS.CREATED_BY
            )
VALUES (@maxPENDAPP_CUSTOMER_CONTACTS_PKEY, @p_CustomerContactId, @FIRST_NAME, @MIDDLE_NAME, @LAST_NAME, @CONTACT_TYPE, @STATUS, @EMPLOYEE_ID, @EMPLOYEE_TYPE, @JOB_TITLE, @EMAIL_ADDRESS, @PHONE_NO, @COLLECTOR_FLAG, 
        @SALES_REP_FLAG, @EFF_START_DATE, @EFF_END_DATE, @ISREJECTED, @ISAPPROVED, @currentUserName, GETDATE(), @comment, 
        @SOURCE_SYSTEM_REFERENCE_TYPE, @SOURCE_SYSTEM_REFERENCE, @SOURCE_SYSTEM_NAME, @MANAGER_FLAG, @CUSTOMER_CONTACTS_PKEY, @p_GoldenAccountId, 'Y', 
        WHEN @p_CustomerContactId = 0 THEN "ADD" ELSE "ASSIGN" END, @LOGITECH_ACCOUNT_ID, @PRIMARY_MANAGER_FLAG, @currentUserName)
        
        
        

   
   
   
