/** Tier */
SELECT GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID AS ID, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE as TIER
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D, PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D
WHERE GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID=GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID
	AND GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME = 'TIER'
    AND GOLDEN_ACCOUNT_ATTR_TYPE_D.CURRENT_VERSION_FLAG = 'Y'
    AND GOLDEN_ACCOUNT_ATTR_LOV_D.CURRENT_VERSION_FLAG='Y'
ORDER BY GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE

/** Strategic Importance */
SELECT GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID AS ID, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE AS STATERGIC_IMPORTANCE
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D, PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D
WHERE GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID=GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID
	AND GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME = 'STRATEGIC_IMPORTANCE'
    AND GOLDEN_ACCOUNT_ATTR_TYPE_D.CURRENT_VERSION_FLAG = 'Y'
    AND GOLDEN_ACCOUNT_ATTR_LOV_D.CURRENT_VERSION_FLAG='Y'
ORDER BY GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE
CHANGE_APPROVAL_COMMENTS 
/** Country */
SELECT DISTINCT COUNTRY, ERP_COUNTRY_CD, REGION
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE COUNTRY <> '' AND ERP_COUNTRY_CD <> '' AND REGION <> '' AND CURRENT_VERSION_FLAG = 'Y'
GROUP BY ERP_COUNTRY_CD, COUNTRY, REGION
ORDER BY COUNTRY

SELECT DISTINCT COUNTRY, ERP_COUNTRY_CD
FROM PRESENTATION.GOLDEN_ACCOUNT_D 
WHERE CURRENT_VERSION_FLAG='Y' AND COUNTRY IS NOT NULL AND ERP_COUNTRY_CD IS NOT NULL
ORDER BY COUNTRY

SELECT DISTINCT COUNTRY, ERP_COUNTRY_CD
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE REGION='Europe' 
	AND GOLDEN_ACCOUNT_D.CURRENT_VERSION_FLAG='Y' 
ORDER BY COUNTRY

/*SELECT * FROM PRESENTATION.COUNTRY_CURRENCY_ASSIGNMENT*/

/** Classification Type */
SELECT GOLDEN_ACCOUNT_ATTR_TYPE_ID AS ID, GOLDEN_ACCOUNT_ATTR_TYPE_NAME AS CLASSIFICATION_TYPE 
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D 
WHERE GOLDEN_ACCOUNT_ATTR_TYPE_NAME  
	IN ('PRICING_CLASSIFICATION','CHANNEL_CLASSIFICATION','BUSINESS_TYPE','DR_CUSTOMER_TYPE')
    AND CURRENT_VERSION_FLAG = 'Y' 
ORDER BY GOLDEN_ACCOUNT_ATTR_TYPE_NAME

/** Classification Value */
SELECT GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_LOV_ID AS ID, GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE AS CLASSIFICATION_VALUE,
	GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME AS CLASSIFICATION_TYPE
FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D, PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D
WHERE GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID=GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_TYPE_ID
	AND GOLDEN_ACCOUNT_ATTR_TYPE_D.GOLDEN_ACCOUNT_ATTR_TYPE_NAME IN ('PRICING_CLASSIFICATION','CHANNEL_CLASSIFICATION','BUSINESS_TYPE','DR_CUSTOMER_TYPE')
    AND GOLDEN_ACCOUNT_ATTR_TYPE_D.CURRENT_VERSION_FLAG = 'Y'
    AND GOLDEN_ACCOUNT_ATTR_LOV_D.CURRENT_VERSION_FLAG='Y' 
ORDER BY GOLDEN_ACCOUNT_ATTR_LOV_D.GOLDEN_ACCOUNT_ATTR_VALUE

/** Channel Grouping Parent */
SELECT DISTINCT LOGITECH_PARTY_NAME
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE CURRENT_VERSION_FLAG = 'Y'
	/*AND LOGITECH_PARTY_NAME  LIKE '%@inputKeyward%'*/
GROUP BY LOGITECH_PARTY_NAME
ORDER BY LOGITECH_PARTY_NAME

/** Industry Code */
SELECT DISTINCT INDUSTRY_CODE
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE CURRENT_VERSION_FLAG = 'Y' 
	AND INDUSTRY_CODE <> '-' AND INDUSTRY_CODE <> '_-' AND INDUSTRY_CODE IS NOT NULL 
	/*AND GOLDEN_ACCOUNT_D.INDUSTRY_CODE  LIKE '%Farming%'*/
ORDER BY INDUSTRY_CODE

/** Region */
SELECT DISTINCT REGION
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE CURRENT_VERSION_FLAG = 'Y' AND REGION IS NOT NULL 
ORDER BY REGION

/** T3 Master Identifier */
SELECT DISTINCT T3_MASTER_IDENTIFIER
FROM PRESENTATION.GOLDEN_ACCOUNT_D
WHERE  CURRENT_VERSION_FLAG = 'Y' AND T3_MASTER_IDENTIFIER IS NOT NULL 
ORDER BY T3_MASTER_IDENTIFIER

SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_D

/** Search Golden Account Form */
SELECT DISTINCT(m.GOLDEN_ACCOUNT_ID), m.GOLDEN_ACCOUNT_NAME, m.LOGITECH_ACCOUNT_ID, m.ACCOUNT_NUMBER, m.ZYME_ID,
		m.VALID_ZYME_ID, m.COUNTRY, m.REGION, m.CUST_NMBR_AT_DIST, m.EXCLUDE_MATCH_FLAG,
		/*CASE WHEN GOLDEN_ACCOUNT_BRIDGE.GOLDEN_ACCOUNT_ID IS NULL THEN 'SHELL' ELSE 'NO SHELL' END SHELL_OR_NOT,*/
        m.T3_MASTER_IDENTIFIER, m.INDUSTRY_CODE
FROM PRESENTATION.GOLDEN_ACCOUNT_D m
/*LEFT JOIN PRESENTATION.GOLDEN_ACCOUNT_BRIDGE ON m.GOLDEN_ACCOUNT_ID = GOLDEN_ACCOUNT_BRIDGE.GOLDEN_ACCOUNT_ID AND GOLDEN_ACCOUNT_BRIDGE.CURRENT_VERSION_FLAG = 'Y'*/
JOIN PRESENTATION.GOLDEN_ACCOUNT_ATTR_BRIDGE ON m.GOLDEN_ACCOUNT_ID = GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ID AND GOLDEN_ACCOUNT_ATTR_BRIDGE.CURRENT_VERSION_FLAG = 'Y'
WHERE m.CURRENT_VERSION_FLAG = 'Y' 
		AND (GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ATTR_LOV_ID = 1 OR GOLDEN_ACCOUNT_ATTR_BRIDGE.GOLDEN_ACCOUNT_ATTR_LOV_ID = 11) /* where tier is Unassigned and STRATEGIC_IMPORTANCE is Unassigned */
		/*AND m.ACCOUNT_NUMBER = '10018' */
		/*AND m.LOGITECH_ACCOUNT_ID = 'A10947393' */
		/*AND m.ZYME_ID = '1' */
		/*AND m.VALID_ZYME_ID = '' */
		/*AND UPPER(m.GOLDEN_ACCOUNT_NAME) LIKE '%INTEGRAL OFFICE%' */
		/*AND UPPER(m.VALID_ZYME_BUSINESS_NAME) LIKE '%ME%'*/
		/*AND m.ERP_COUNTRY_CD = 'ES' */
		/*AND m.REGION = 'Europe' */
		/*AND m.T3_MASTER_IDENTIFIER like ''*/
		/*AND m.INDUSTRY_CODE = ''*/
		/*AND m.LOGITECH_PARTY_NAME = 'Integral Office Comunicaciones Sl Total'*/
ORDER BY m.GOLDEN_ACCOUNT_ID
LIMIT 200
OFFSET 0