SELECT * FROM PRESENTATION.CUSTOMER_ACCOUNT_D;
SELECT * FROM PRESENTATION.CUSTOMER_CONTACTS_BRIDGE;
SELECT * FROM PRESENTATION.CUSTOMER_CONTACTS_D;
SELECT * FROM PRESENTATION.CUSTOMER_LOCATION_BRIDGE;
SELECT * FROM PRESENTATION.CUSTOMER_LOCATION_D;
SELECT * FROM PRESENTATION.CUSTOMER_SITE_D;
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_BRIDGE WHERE GOLDEN_ACCOUNT_ID = 10000000655297;
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_LOV_D WHERE GOLDEN_ACCOUNT_ATTR_TYPE_ID = 3;
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_ATTR_TYPE_D; 
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_BRIDGE;
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_D;
SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_TYPE_D;

SELECT * FROM PRESENTATION.PENDINGAPPROVALCONTACTS;
SELECT * FROM PRESENTATION.PENDINGAPPROVALXREFACCOUNT;

SELECT * FROM PRESENTATION.PENDINGAPPROVALATTRIBUTE WHERE CURRENTVALUE = 'BEST BUY WW';

SELECT * FROM PRESENTATION.PENDINGAPPROVALXREFACCOUNT;

SELECT * FROM PRESENTATION.GOLDEN_ACCOUNT_D WHERE GOLDEN_ACCOUNT_ID = 10000000655297;

SELECT * FROM PRESENTATION.COUNTRY_GEO_D;

